# -*- mode: ruby -*-
# vi: set ft=ruby :

$postgres = <<POSTGRESQL
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update
    sudo apt-get install postgresql -y
POSTGRESQL

$mysql = <<MYSQL
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password password'
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password'
    sudo apt-get install mysql-server mysql-client -y
MYSQL


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 5432, host: 55432

  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2560
     vb.cpus = 2
     vb.name = "PostgreSQL-Test"
  end

  config.vm.provision "shell", inline: $postgres
  config.vm.provision "shell", inline: $mysql
end
